name: keymaps

on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    env:
      QMK_HOME: ${{ github.workspace }}/qmk_firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt update -y

      - run: sudo apt install -y shellcheck
      - run: shellcheck bin/*

      - run: sudo apt install -y git python3-pip
      - run: python3 -m pip install --user qmk

      - run: echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - run: make qmk

      - run: cd $QMK_HOME && sudo util/qmk_install.sh -y

      - run: make

      - run: make test

      - uses: actions/upload-artifact@v3
        with:
          name: patcoll-hexes
          path: ${{ github.workspace }}/qmk_firmware/*.hex

